/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package university_system;

/**
 *
 * @author DELL
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class searchdeletestudents extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
     String url = "jdbc:sqlserver://DESKTOP-UOH80G4;databaseName=university_system;encrypt=true;trustServerCertificate=true;user=sa;password=Sherin00/*;";
    public searchdeletestudents() {
        initComponents();
        

           try {
       Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
       }
       catch(ClassNotFoundException ex){
       JOptionPane.showMessageDialog(this, "Cannot load JDBC Driver !!!");
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        student_table = new javax.swing.JTable();
        search_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        search_class_btn1 = new javax.swing.JButton();
        class_text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        class_txt = new javax.swing.JTextField();
        delete_class_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("SEARCH & DELETE STUDENTS ");

        student_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "FATHER NAME", "PHONE", "FATHER PHONE", "CLASS", "ROLL NUMBER", "ROLL NUMBER"
            }
        ));
        jScrollPane1.setViewportView(student_table);

        search_btn.setText("SEARCH");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("To Delete, Insert the ID :");

        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("BACK");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });

        jLabel4.setText("To Search about specific student, Insert the ID :");

        search_class_btn1.setText("SEARCH");
        search_class_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_class_btn1ActionPerformed(evt);
            }
        });

        class_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_textActionPerformed(evt);
            }
        });

        jLabel5.setText("To Search about specific class, Insert the class number :");

        jLabel6.setText("To Delete specific class, Insert the class number :");

        class_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_txtActionPerformed(evt);
            }
        });

        delete_class_btn1.setText("Delete");
        delete_class_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_class_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_btn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(class_text, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_class_btn1)))
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(class_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_class_btn1))
                    .addComponent(jLabel6))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_btn)
                            .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_class_btn1)
                            .addComponent(class_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete_class_btn1)
                            .addComponent(class_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        String inputId = id_txt.getText();
        Connection conn = null;
        PreparedStatement ptstat = null;
        try{
            conn = DriverManager.getConnection(url);
            
            String query = "SELECT * FROM students where id = ? ;";
             ptstat = conn.prepareStatement(query);
             ptstat.setString(1, inputId);
            ResultSet result = ptstat.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)student_table.getModel();
            tm.setRowCount(0);
                if (result.next()) {
        Object[] row = {
            result.getInt("id"),
            result.getString("name"),
            result.getString("father_name"),
            result.getString("phone"),
            result.getString("father_phone"),
            result.getString("class"),
            result.getString("roll"),
            result.getString("address")
        };
        tm.addRow(row);
    } else {
        JOptionPane.showMessageDialog(this, "No student found with this ID.");
    }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
        finally{
         if(conn != null){try{conn.close();}catch(Exception ex){}}
         if(ptstat != null){try{ptstat.close();}catch(Exception ex){}}
         }
         
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        String id = id_text.getText();
        
             Connection conn = null;
        PreparedStatement ptstat = null;
        try{
            conn = DriverManager.getConnection(url);
            
            String query = "DELETE  FROM students WHERE id = '"+id+"'  ;";
            ptstat = conn.prepareStatement(query);
           ptstat.executeUpdate();
           JOptionPane.showMessageDialog(this, "Data has been Deleted !!!");
           id_text.setText("");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
        finally{
         if(conn != null){try{conn.close();}catch(Exception ex){}}
         if(ptstat != null){try{ptstat.close();}catch(Exception ex){}}
         }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        studentsmodule obj = new studentsmodule();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void search_class_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_class_btn1ActionPerformed
           String inputClass = class_text.getText();
        Connection conn = null;
        PreparedStatement ptstat = null;
        try{
            conn = DriverManager.getConnection(url);
            
            String query = "SELECT * FROM students where class = ? ;";
             ptstat = conn.prepareStatement(query);
             ptstat.setString(1, inputClass);
            ResultSet result = ptstat.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)student_table.getModel();
            tm.setRowCount(0);
            boolean found = false;    
            while (result.next()) {
        Object[] row = {
            result.getInt("id"),
            result.getString("name"),
            result.getString("father_name"),
            result.getString("phone"),
            result.getString("father_phone"),
            result.getString("class"),
            result.getString("roll"),
            result.getString("address")
        };
        tm.addRow(row);
        found = true;
    }
          if(!found){
              JOptionPane.showMessageDialog(this, "There is no Students in this Class !!!");
          }  
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
        finally{
         if(conn != null){try{conn.close();}catch(Exception ex){}}
         if(ptstat != null){try{ptstat.close();}catch(Exception ex){}}
         }
    }//GEN-LAST:event_search_class_btn1ActionPerformed

    private void class_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class_textActionPerformed

    private void class_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class_txtActionPerformed

    private void delete_class_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_class_btn1ActionPerformed
        // TODO add your handling code here:
        
           String classInput = class_txt.getText();
        
             Connection conn = null;
        PreparedStatement ptstat = null;
        try{
            conn = DriverManager.getConnection(url);
            
            String query = "DELETE  FROM students WHERE class = ?  ;";
            
            ptstat = conn.prepareStatement(query);
            ptstat.setString(1, classInput);
           int rowsAffected = ptstat.executeUpdate();
           if(rowsAffected > 0){
               JOptionPane.showMessageDialog(this, "Data has been Deleted !!!");
           }
           else{
               JOptionPane.showMessageDialog(this, "No students found in this class !!!");
           }
           class_txt.setText("");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
        finally{
         if(conn != null){try{conn.close();}catch(Exception ex){}}
         if(ptstat != null){try{ptstat.close();}catch(Exception ex){}}
         }
    }//GEN-LAST:event_delete_class_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchdeletestudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchdeletestudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchdeletestudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchdeletestudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchdeletestudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField class_text;
    private javax.swing.JTextField class_txt;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton delete_class_btn1;
    private javax.swing.JTextField id_text;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton search_class_btn1;
    private javax.swing.JTable student_table;
    // End of variables declaration//GEN-END:variables
}
